language: ruby
rvm:
  - 2.0.0
env:
  - ARES_SERVER=ares.int.misfit.com
  - ARES_USER=misfit
  # ARES_PASSWORD=[secure]
  - secure: "n4h8coLOFxbcYwUDPChtygZYk0Y8qY8YPUJtAtcTjTgVWkNDfeHrhvAQlRSY3ay71niD4ndakQjUvNEYdAZEq4iNsW+2rgJ+/OMNuGcW2SrHhOnQNrYWV5UX5EyGzmfNHU1GUeJFmj/VaTcIUiLuy5BIDZiFv2PmxXdMiWA1TpdPvc+UZ4Kje4J0hRjqFqpJ4P5GTfIJH2SJ67PSXXGI+WWI09cdIkhSGRk+6QPIWJjjDMwmeGF+6MtmiJUto7nskBAzARhukaxvtwxJwzRLDUF0mrjXN5OvT5mHXociFfWke6SXtGgBg/yw4DGEgc/z1jCFzGRE+07N7BENcUz8kpNhOPmaHrXzAApPfIEhlz7rsl6YTMotQfd10x812Edzxr6T+9KJ2ty9gxPqxxrIqnXvm++j5EZRIqHOEWYIGnAjPJHH/huesn0VDMvw59b6lC6rYkvjOgn/C9gdLm20iG/K5s1oFMP4kQ8t+pVxQym/9+JzvTG5z1F62Zk+HTiz8vNoLW7SpilYxJGVrkIeYx4avtQ7XLHGOsVCaadomriYMjbBduUiPJeY7hENHC3Ew8DljhDCuCFm1InXFv+T3JYs7l0N7VFg3eOVF1i8TkvGRHNBHmdUmAtwKeyY7KkNa4Ut51qBa6pKlavYRPgw/GYiAIhsZyf1xihA8+kdQZw="

install:
  - bundle install
  - ls vendor/bundle
before_script:
  - rake db:migrate
  # - curl http://$ARES_SERVER/downloads/ares-linux-386.tar.gz | tar xzv

script:
  - rake test
  # - ./ares

# deploy:
#   provider: s3
#   access_key_id: AKIAISQD2KKR4SJKP5NQ
#   secret_access_key:
#     secure: pp5AYuCTzHlU2u0xOG5rNXFNO3H0tAhmjUPXWuM3A4WMaSOC11ZX1/R2JdMFS5kEff57uLFXXjyGl2M7pI/ojKaZoNFPLmN+D87+S8vzCWDgEXvUIWuCzCBrK2xqIhnP2A5TlC31njr6obd/6v0ll1mv2IZeGS1MauJkoKMpCiVv7VKChKBp0C5Aemw1pm5jBJ/+rUQIuQqg3J9am+gS91v4FXptedZxd6VVXdUO24SrCRHNdhtwm8wGQJkYgxj+nbp+3oeKhB1HiFf/C+KfO+89/O675a+gbVCE10Ie2UsykFEbG9tGOTSXgLbSqglMiPrgmXUmzJc02C0IXnxI4O4yBxtpVmOXIEHlFm79zQLmfv2cJyefLBGAIL5vBL3gTVebg9HLXoZkE6FbFBSC8GXRXXltixKzjlyqNFVwj4dTYhdKc7HeSopyv6fimaTJvJXNp2neHpUzY2B0+3foCg/4ZhHxlOXuC0Kd+/oTYMXgVpaBGfevO5Dy3/3CPnTNgSUQo86u/6sGxg85L4vbwcIawrzR50vlD8/vwRPOjwd2gRqEz+RE2iPgOZVEpygYapSZYJx8jYunFiDNBP7VxCGe8dZ7uIiRv5bVQJhHAkDVNRFGKGYPSk1tJbvcCfOKAlB3/MwljTomHcVljiJr5MNhDqy1rwlWYLkCG4NdnTI=
#   bucket: misfit.sw.stg.epd-team
#   upload-dir: 'westmisfit/rails-hello/build_${TRAVIS_BUILD_NUMBER}'
#   acl: public_read
#   on:
#     repo: westmisfit/rails-hello
#     branch: develop

cache:
  directories:
    - vendor/bundle

# branches:
#   only:
#     - master
#     - develop

# notifications:
#   hipchat: C5Ta9DcFxSNftnD2ZMtfRJN2SbUtRLuGDQy6JXmI@1467331
